In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv('Bank Churn Modelling.csv')  #Bank Churn Modelling.csv

In [3]:
df

CustomerId    Surname  CreditScore Geography  Gender  Age  Tenure  \
0       15634602   Hargrave          619    France  Female   42       2   
1       15647311       Hill          608     Spain  Female   41       1   
2       15619304       Onio          502    France  Female   42       8   
3       15701354       Boni          699    France  Female   39       1   
4       15737888   Mitchell          850     Spain  Female   43       2   
...          ...        ...          ...       ...     ...  ...     ...   
9995    15606229   Obijiaku          771    France    Male   39       5   
9996    15569892  Johnstone          516    France    Male   35      10   
9997    15584532        Liu          709    France  Female   36       7   
9998    15682355  Sabbatini          772   Germany    Male   42       3   
9999    15628319     Walker          792    France  Female   28       4   

        Balance  Num Of Products  Has Credit Card  Is Active Member  \
0          0.00                1                1                 1   
1      83807.86                1                0                 1   
2     159660.80                3                1                 0   
3          0.00                2                0                 0   
4     125510.82                1                1                 1   
...         ...              ...              ...               ...   
9995       0.00                2                1                 0   
9996   57369.61                1                1                 1   
9997       0.00                1                0                 1   
9998   75075.31                2                1                 0   
9999  130142.79                1                1                 0   

      Estimated Salary  Churn  
0            101348.88      1  
1            112542.58      0  
2            113931.57      1  
3             93826.63      0  
4             79084.10      0  
...                ...    ...  
9995          96270.64      0  
9996         101699.77      0  
9997          42085.58      1  
9998          92888.52      1  
9999          38190.78      0  

[10000 rows x 13 columns]

In [4]:
#declaring the features(CreditScore	 Geography	 Gender	 Age	 Tenure	 Balance	 Num Of Products	 Has Credit Card	 Is Active Member	 Estimated Salary	)
#and label (Churn)
X= df.iloc[:,2:12].values
Y =df.iloc[:,12].values

#in df.iloc[:,:] the first semicolomn defines the rows if left blank(i.e. :) then it selects all rows 
#the 2nd semicolon defines the columns 

In [5]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [6]:
Y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [7]:
#using Label encoder to encode gender 
from sklearn.preprocessing import LabelEncoder , OneHotEncoder

In [8]:
le_X_2=LabelEncoder()

In [9]:
X[:,2]=le_X_2.fit_transform(X[:,2])

In [10]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [11]:
#using onehot  encoder to encode geography 
from sklearn.compose import ColumnTransformer

In [12]:
ct = ColumnTransformer([('ohe', OneHotEncoder(), [1])], remainder='passthrough')

In [13]:
X = np.array(ct.fit_transform(X), dtype = np.str_) #.toarray()

In [14]:
X = X[:, 1:]

In [15]:
print(X)

[['0.0' '0.0' '619' ... '1' '1' '101348.88']
 ['0.0' '1.0' '608' ... '0' '1' '112542.58']
 ['0.0' '0.0' '502' ... '1' '0' '113931.57']
 ...
 ['0.0' '0.0' '709' ... '0' '1' '42085.58']
 ['1.0' '0.0' '772' ... '1' '0' '92888.52']
 ['0.0' '0.0' '792' ... '1' '0' '38190.78']]


In [16]:
from sklearn.model_selection import train_test_split 

In [17]:
X_train, X_test, y_train, y_test = train_test_split( X , Y , test_size = 0.2 ,random_state=118 )

# Feature Scaling


In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
sc = StandardScaler()

In [20]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [21]:
pd.DataFrame(X_train)

0         1         2         3         4         5         6   \
0    -0.576003 -0.574271 -2.059431  0.917399 -0.375364 -0.347638  1.149324   
1    -0.576003 -0.574271  1.010330  0.917399  2.028735 -1.731959  1.216015   
2     1.736102 -0.574271 -1.115687  0.917399 -0.856184  0.344523 -0.047151   
3    -0.576003 -0.574271 -1.240137  0.917399  0.490112 -0.693718 -1.224238   
4    -0.576003  1.741338  0.968847 -1.090038 -0.856184 -1.385878  0.762705   
...        ...       ...       ...       ...       ...       ...       ...   
7995  1.736102 -0.574271 -1.115687 -1.090038  1.740243 -1.385878  0.475983   
7996 -0.576003 -0.574271  0.958476  0.917399 -0.663856  1.382764 -1.224238   
7997 -0.576003 -0.574271  0.097698 -1.090038 -0.375364  0.344523  0.389969   
7998 -0.576003 -0.574271 -1.032721 -1.090038  1.932571 -1.039798  1.450413   
7999  1.736102 -0.574271 -0.835675  0.917399 -0.086872 -1.385878  0.813394   

            7         8         9         10  
0    -0.918154  0.649397  0.964625 -1.678291  
1    -0.918154  0.649397 -1.036672  0.456508  
2    -0.918154  0.649397  0.964625  1.326492  
3     0.801638  0.649397  0.964625 -1.151572  
4    -0.918154  0.649397  0.964625  0.725913  
...        ...       ...       ...       ...  
7995  0.801638  0.649397  0.964625  0.350506  
7996  0.801638  0.649397 -1.036672  1.301413  
7997 -0.918154  0.649397 -1.036672 -1.416615  
7998 -0.918154  0.649397 -1.036672  1.026759  
7999 -0.918154  0.649397 -1.036672  0.812256  

[8000 rows x 11 columns]

In [22]:
!pip install keras

In [23]:
!pip install tensorflow

In [24]:
from keras.models import Sequential 

In [25]:
from keras.layers import Dense

In [26]:
classifier = Sequential()

Input layer + 1st Hidden layer

In [27]:
classifier.add(Dense(units = 6 ,kernel_initializer ='uniform' , activation = 'relu' ,input_dim = 11 ))

# units (last layer neurons)
# kernel_initializer (function to initialize weights) = uniform (i.e. all weights are uniformly distributed) 
# activation (activation function )
# input_dim(dimension of input neurons) = 11 input neurons


2nd Hidden Layer

In [28]:
classifier.add(Dense(units = 6, kernel_initializer = 'uniform' , activation = 'relu'))

#we don't provide input_dim because it automatically connectswith the previous layer
#the 6 neurons from previous layer acts as input to this layer 
#this layer also contains 6 neurons

Output Layer

In [29]:
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid' ))

# here we have only 1 neuron because we have to predict whether the customer will stay or leave (i.e 0 or 1)
# Also we have used sigmoid activation function because it provides the probability whether the customer will stay or leave

In [34]:
classifier.compile ( optimizer = 'adam', loss = 'binary_crossentropy ' , metrics = ['accuracy'])

# optimizer (method to compile the artifical neural networks together) = 'adam' (it performs the stochastic gradient descent optimizer tecnique )
# loss (optimization function used in case of training classification models)
# binary_crossentropy = it computes the cross entropy loss between true lablels and predicted lables

# Fit dataset to the ANN model

In [38]:
classifier.fit(X_train, y_train, batch_size = 10 ,epochs = 100)
# X_train = input layer neuron
# y_train = output layer neuron
# epoch = no of times an algo visits the dataset 



Epoch 1/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3872 - accuracy: 0.8411
Epoch 2/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3870 - accuracy: 0.8406
Epoch 3/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3835 - accuracy: 0.8421
Epoch 4/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3786 - accuracy: 0.8440
Epoch 5/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3736 - accuracy: 0.8474
Epoch 6/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3674 - accuracy: 0.8501
Epoch 7/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3594 - accuracy: 0.8512
Epoch 8/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3487 - accuracy: 0.8591
Epoch 9/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3433 - accuracy: 0.8620
Epoch 10/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3414 - accura

800/800 [==============================] - 1s 1ms/step - loss: 0.3265 - accuracy: 0.8668
Epoch 82/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3263 - accuracy: 0.8671
Epoch 83/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3262 - accuracy: 0.8684
Epoch 84/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3264 - accuracy: 0.8675
Epoch 85/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3258 - accuracy: 0.8662
Epoch 86/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3261 - accuracy: 0.8676
Epoch 87/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3262 - accuracy: 0.8675
Epoch 88/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3255 - accuracy: 0.8673
Epoch 89/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3261 - accuracy: 0.8662
Epoch 90/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3258 - accuracy: 

In [39]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred>0.5)

63/63 [==============================] - 0s 1ms/step


In [40]:
print(y_pred)

[[ True]
 [False]
 [False]
 ...
 [ True]
 [False]
 [False]]


In [42]:
from sklearn.metrics import confusion_matrix , accuracy_score
cm = confusion_matrix(y_test, y_pred)

In [43]:
print(cm)

[[1510   83]
 [ 203  204]]


In [44]:
accuracy_score(y_test,y_pred )

0.857